# Generated by Django 4.2.5 on 2023-11-23 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_consumo_dateconsumption_sell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sellsaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateSellSaved', models.DateTimeField(auto_now_add=True)),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.consumo')),
                ('totalConsumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.sell')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
