# Generated by Django 4.2.5 on 2023-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_sellsaved'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellsaved',
            name='cantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
