# Generated by Django 4.2.5 on 2023-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_sellsaved_consumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellsaved',
            name='consumption',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sellsaved',
            name='totalConsumption',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
