# Generated by Django 4.2.5 on 2023-11-23 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_sellsaved_totalconsumption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellsaved',
            name='consumption',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sellsaved',
            name='totalConsumption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.sell'),
        ),
    ]
