# Generated by Django 4.2.5 on 2023-11-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_sellsaved_consumption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellsaved',
            name='totalConsumption',
            field=models.DecimalField(decimal_places=2, max_digits=18, null=True),
        ),
    ]
